### ISSUE TITLE
Simulation parameters

### ISSUE THREAD

**Issue by jeancharles-roger** [jeancharles-roger/matrixstudio#4]
Simulation should be parameterised with constants (float, int, ulong) accessible from:
- OpenCL kernels and libraries,
- Tasks parameters and
- Matrix parameters.

A new control panel on the south to configure will be added to configure them.

**Comment by jeancharles-roger** [comment]
@pascal-ballet do you think matrices sizes could be parameterised ?

**Comment by pascal-ballet** [comment]
Yes, without any doubt.

2016-06-04 17:51 GMT+02:00 Jean-Charles Roger <notifications@github.com>:

**Comment by jeancharles-roger** [comment]
Every parameterable field will be a statically computable formula. 

It will support:
- simple numeric expressions: `+`, `-`, `*`, `/`, `%` with common priorities,
- parenthesis,
- access to parameters (parameters will be able to access parameters that defined upstream in the list).

A validation for all parameter able fields will present errors if the expression can't be computed.

**Comment by pascal-ballet** [comment]
After the definition of global parameters by the user, it could be interesting to add an automatic  definiton for the matrix sizes. For example a matrix, called Mat, with a size (100,100,1) will have the global parameters automatically added: mat_SX = 100; Mat_SY = 100 and Mat_SZ = 1; If the Mat size is (param1, param2, 1), the added parameters will be: Mat_SX = param1; Mat_SY = param2; Mat_SZ = 1;
Thus, the sizes of matrices that now are kernel parameters, will be removed (the codes already made will still work because the names of the variable remain the same).

**Comment by pascal-ballet** [comment]
Again concerning the parameters, it could be usefull to remove or re-add some matrices or others (step, mouse, etc). So the kernel parameters will be more clear !

**Comment by jeancharles-roger** [comment]
So what you're saying is that for each matrix, 3 simulation parameters will be added: on for the size on x, one for y and one for z. Moving the value for the matrix sizes from MatrixController to the new parameter panel. Thus reducing the kernel prototype length.

**Comment by jeancharles-roger** [comment]
Concerning mouse pointer and step, there aren't simulation parameters and they're constant. I think it would be confusing.

**Comment by jeancharles-roger** [comment]
I'm writing specifications on the wiki: [Parameters](../wiki/Parameters).

**Comment by pascal-ballet** [comment]
Exception when removing the last kernel in a MS task:

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.xid.basics.ui.field.ListField$2.handleEvent(ListField.java:112)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
	at org.eclipse.swt.widgets.Table.checkData(Table.java:1180)
	at org.eclipse.swt.widgets.Table.wmNotifyChild(Table.java:6831)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5690)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1956)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5242)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4718)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5063)
	at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2443)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:578)
	at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:444)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4760)
	at org.eclipse.swt.widgets.Table.windowProc(Table.java:5983)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
	at org.eclipse.swt.internal.win32.OS.SendMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.SendMessage(OS.java:3302)
	at org.eclipse.swt.widgets.Table.clearAll(Table.java:1455)
	at org.xid.basics.ui.field.ListField.refresh(ListField.java:286)
	at org.xid.basics.ui.field.ListField.setValue(ListField.java:274)
	at org.xid.basics.ui.field.ListField.setValue(ListField.java:280)
	at matrixstudio.ui.controller.TaskController.refreshFields(TaskController.java:186)
	at org.xid.basics.ui.field.PropertiesField.setSubject(PropertiesField.java:113)
	at matrixstudio.ui.MatrixStudio.setSelection(MatrixStudio.java:256)
	at matrixstudio.ui.ScheduleTabController$1.notified(ScheduleTabController.java:37)
	at org.xid.basics.notification.NotificationSupport$Stub.fireNotification(NotificationSupport.java:37)
	at org.xid.basics.notification.NotificationSupport$Stub.fireValueNotification(NotificationSupport.java:47)
	at org.xid.basics.ui.diagram.DiagramController.fireProperty(DiagramController.java:106)
	at org.xid.basics.ui.diagram.DiagramController.setSelectedElements(DiagramController.java:533)
	at org.xid.basics.ui.diagram.DiagramController.findSelectionNewElements(DiagramController.java:814)
	at org.xid.basics.ui.diagram.DiagramController.refreshElements(DiagramController.java:353)
	at org.xid.basics.ui.field.DiagramField.refreshDiagram(DiagramField.java:133)
	at matrixstudio.ui.ScheduleTabController.refreshFields(ScheduleTabController.java:54)
	at matrixstudio.ui.MatrixStudio.refreshSchedule(MatrixStudio.java:215)
	at matrixstudio.ui.MatrixStudio.refreshFields(MatrixStudio.java:194)
	at matrixstudio.ui.MatrixStudio$1.executeAction(MatrixStudio.java:80)
	at org.xid.basics.ui.action.ActionManager$1.handleEvent(ActionManager.java:57)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
	at matrixstudio.ui.MatrixStudio.open(MatrixStudio.java:467)
	at matrixstudio.ui.MatrixStudio.main(MatrixStudio.java:511)

**Comment by pascal-ballet** [comment]
![image](https://cloud.githubusercontent.com/assets/15141444/18544466/f73a0afe-7b34-11e6-9e88-f84e88daaf6b.png)

**Comment by pascal-ballet** [comment]
This event is called twice. The above screencapture is for the 2nd call after deleting the kernel in the task. The second item (index 1) is empty.

**Comment by jeancharles-roger** [comment]
I'm working on the computed parameters. It'll lead me to some changes in the Simulator, I'll pushed them to the branch `parameters`.

**Comment by jeancharles-roger** [comment]
The branch is merged
