### ISSUE TITLE
Problem when moving kernels in a task

### ISSUE THREAD

**Issue by jeancharles-roger** [jeancharles-roger/matrixstudio#6]
From @pascal-ballet.

An exception occurs:
```
Exception when removing the last kernel in a MS task:
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at org.xid.basics.ui.field.ListField$2.handleEvent(ListField.java:112)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1137)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1122)
at org.eclipse.swt.widgets.Table.checkData(Table.java:1180)
at org.eclipse.swt.widgets.Table.wmNotifyChild(Table.java:6831)
at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5690)
at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1956)
at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5242)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4718)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5063)
at org.eclipse.swt.internal.win32.OS.CallWindowProcW(Native Method)
at org.eclipse.swt.internal.win32.OS.CallWindowProc(OS.java:2443)
at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:578)
at org.eclipse.swt.widgets.Table.callWindowProc(Table.java:444)
at org.eclipse.swt.widgets.Control.windowProc(Control.java:4760)
at org.eclipse.swt.widgets.Table.windowProc(Table.java:5983)
at org.eclipse.swt.widgets.Display.windowProc(Display.java:5050)
at org.eclipse.swt.internal.win32.OS.SendMessageW(Native Method)
at org.eclipse.swt.internal.win32.OS.SendMessage(OS.java:3302)
at org.eclipse.swt.widgets.Table.clearAll(Table.java:1455)
at org.xid.basics.ui.field.ListField.refresh(ListField.java:286)
at org.xid.basics.ui.field.ListField.setValue(ListField.java:274)
at org.xid.basics.ui.field.ListField.setValue(ListField.java:280)
at matrixstudio.ui.controller.TaskController.refreshFields(TaskController.java:186)
at org.xid.basics.ui.field.PropertiesField.setSubject(PropertiesField.java:113)
at matrixstudio.ui.MatrixStudio.setSelection(MatrixStudio.java:256)
at matrixstudio.ui.ScheduleTabController$1.notified(ScheduleTabController.java:37)
at org.xid.basics.notification.NotificationSupport$Stub.fireNotification(NotificationSupport.java:37)
at org.xid.basics.notification.NotificationSupport$Stub.fireValueNotification(NotificationSupport.java:47)
at org.xid.basics.ui.diagram.DiagramController.fireProperty(DiagramController.java:106)
at org.xid.basics.ui.diagram.DiagramController.setSelectedElements(DiagramController.java:533)
at org.xid.basics.ui.diagram.DiagramController.findSelectionNewElements(DiagramController.java:814)
at org.xid.basics.ui.diagram.DiagramController.refreshElements(DiagramController.java:353)
at org.xid.basics.ui.field.DiagramField.refreshDiagram(DiagramField.java:133)
at matrixstudio.ui.ScheduleTabController.refreshFields(ScheduleTabController.java:54)
at matrixstudio.ui.MatrixStudio.refreshSchedule(MatrixStudio.java:215)
at matrixstudio.ui.MatrixStudio.refreshFields(MatrixStudio.java:194)
at matrixstudio.ui.MatrixStudio$1.executeAction(MatrixStudio.java:80)
at org.xid.basics.ui.action.ActionManager$1.handleEvent(ActionManager.java:57)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4362)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1113)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4180)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3769)
at matrixstudio.ui.MatrixStudio.open(MatrixStudio.java:467)
at matrixstudio.ui.MatrixStudio.main(MatrixStudio.java:511)
```

**Comment by jeancharles-roger** [comment]
I can't reproduce it.
Can you give a bit more details ?

**Comment by pascal-ballet** [comment]
1) Go to the kernel1, and add the following code (I think this code it do NOT matter, but I repeat exactly what I done):
Matrix1[p]++;

2) Go to the Scheduler tab, select the default task and add again the Kernel1

3) I ran the application for 2 seconds then stopped it.

4) I add again the kernel 1 in the task.

5) I remove one of the kernel (I do not remember which) but then the exception occured each time I remove the last kernel in the list.

**Comment by jeancharles-roger** [comment]
I still can't reproduce the exception. I'll try harder ...

**Comment by jeancharles-roger** [comment]
From @pascal-ballet 
![f73a0afe-7b34-11e6-9e88-f84e88daaf6b](https://cloud.githubusercontent.com/assets/3531483/18549496/1b823048-7b4f-11e6-9b6c-740619785f1d.png)

**Comment by jeancharles-roger** [comment]
From @pascal-ballet 

This event is called twice. The above screencapture is for the 2nd call after deleting the kernel in the task. The second item (index 1) is empty.

**Comment by jeancharles-roger** [comment]
Thank you for the analysis. I'll try to prevent this
